name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  run-checks:
    name: Run Checks
    uses: ./.github/workflows/run-checks.yaml
  deploy-gh-pages:
    name: Deploy to Github Pages
    permissions:
      contents: write
    secrets: inherit
    needs:
     - run-checks
    uses: ./.github/workflows/deploy-gh-pages.yaml