name: On Main push
on:
  push: 
    branches:
      - main
jobs:
  run-ci:
    name: Run CI
    uses: ./.github/workflows/ci.yaml
  deploy-gh-pages:
    name: Deploy to Github Pages
    permissions:
      contents: write
    secrets: inherit
    needs:
     - run-ci
    uses: ./.github/workflows/deploy-gh-pages.yaml